<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>mBar</RootNamespace>
    <AssemblyName>mBar</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>resources\assets\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	  
    <Version>1.3.4</Version><!-- 程序主版本（UpdateChecker / About用） -->
    <AssemblyVersion>1.0.0.0</AssemblyVersion><!-- 稳定不动 -->
    <FileVersion>1.3.4.0</FileVersion><!-- 文件属性显示 -->
  </PropertyGroup>


	<ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="Svg.Skia" Version="4.6.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

    <!-- 自动复制 themes 与 lang 目录下的所有文件 -->
    <ItemGroup>
        <Content Include="resources\themes\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </Content>

        <Content Include="resources\lang\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </Content>

        <Content Include="resources\plugins\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </Content>
    </ItemGroup>
	<ItemGroup>
		<Content Include="resources\mBar.Updater.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	
<ItemGroup>
  <Compile Remove="mBar.Updater\**" />
  <Compile Remove="mBar.Wpf\**" />
  <EmbeddedResource Remove="mBar.Updater\**" />
  <EmbeddedResource Remove="mBar.Wpf\**" />
  <None Remove="mBar.Updater\**" />
  <None Remove="mBar.Wpf\**" />
</ItemGroup>
	
<!-- 引入文件资源管理 -->
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
<!-- 引入文件资源管理 -->
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="src\UI\Settings\" />
  </ItemGroup>
</Project>
