<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Updater 应该是一个完全独立可执行程序 -->
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishTrimmed>false</PublishTrimmed>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>

		<!-- 改名以减少误报 -->
		<AssemblyName>mBar.Updater</AssemblyName>
		<!-- 程序集元数据 (增加可信度) -->
		<Company>mBar</Company>
		<Product>mBar Auto Updater</Product>
		<Description>Automatic update component for mBar system monitoring tool.</Description>
		<Copyright>Copyright © 2025-2026 mBar Team</Copyright>
		<FileVersion>1.2.5.0</FileVersion>
		<AssemblyVersion>1.2.5.0</AssemblyVersion>

		<!-- 禁用顶级语句 -->
		<UseMaui>false</UseMaui>

		<!-- 指定 Main 入口 -->
		<StartupObject>mBar.Updater.Program</StartupObject>
	</PropertyGroup>
</Project>
